module.exports = {
	app_init: 'init',
	checkLogin: 'checkLogin',
	login: 'login',
	logout: 'logout',
	login_setInfo: 'setInfo',
	APP_getItemPrice: 'getItemPrice',
	order_init: 'initDoctor',
	order_initWorker: 'initWorker',
	order_changeConfirmState: 'changeConfirmState',
	order_changeSubmitSate: 'changeSubmitSate',
	BA_init: 'intiState',
	BA_changeConfirmState: 'changeConfirmState',
	BA_changeSubmitSate: 'changeSubmitSate',
	BA_saveSign: 'saveSign',
	BA_savePhysicalExam: 'savePhysicalExam',
	BA_saveNewBorn: 'saveNewBorn',
	BA_savePostpartum: 'savePostpartum',
	NA_saveChronic: 'saveChronic',
	NA_savePolicy: 'savePolicy',
	NA_saveActivity: 'saveActivity',
	NA_saveGravida: 'saveGravida',
	NA_saveChildren: 'saveChildren',
	TR_saveDrug: 'saveDrug',
	TR_saveDrugeffect: 'saveDrugeffect',
	CD_saveBlood:'saveBlood',
	CD_saveSugar: 'saveSugar',
	worker_getOrders: 'getOrders',
	worker_getOrderDetail: 'getOrderDetail',
	worker_saveOrderDetail: 'saveOrderDetail',
};