module.exports = {
	app_init: 'init',
	checkLogin: 'checkLogin',
	login: 'login',
	logout: 'logout',
	login_setInfo: 'setInfo',
	APP_getItemPrice: 'getItemPrice',
	order_init: 'initState',
	order_changeConfirmState: 'changeConfirmState',
	order_changeSubmitSate: 'changeSubmitSate',
	BA_init: 'intiState',
	BA_changeConfirmState: 'changeConfirmState',
	BA_changeSubmitSate: 'changeSubmitSate',
	BA_saveSign: 'saveSign',
	BA_savePhysicalExam: 'savePhysicalExam',
	BA_saveNewBorn: 'saveNewBorn',
	BA_savePostpartum: 'savePostpartum',
	NA_savePolicy: 'savePolicy',
};